import React from "react";
import Navigation from "./lib/Navigation";
import { Toaster } from "react-hot-toast";
import "./global.css";
import "bootstrap/dist/css/bootstrap.css";

export const metadata = {
  title: "Support Worker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Toaster />
        <Navigation className="sticky top-0 z-50" />
        <div className="flex-grow pt-10">{children}</div>
      </body>
    </html>
  );
}
